#! /bin/bash

cmd=$(readlink -f "$0")
scriptdir=$(dirname "$cmd")

rawpreset="$1"
shift

nimg=$#

rm -f exposures.txt images.txt
for i in $(seq 1 $nimg); do
	img="$1"
	aperture=$(exiftool -T -aperture "$img")
	if [ x"${aperture}"x = "x-x" ]; then aperture=8; fi
	
	speed=$(exiftool -T -SonyExposureTime2 "$img")
	echo "SonyExposureTime2: $speed"
	speed=$(exiftool -T -shutterspeed "$img")
	speeds=$(echo "$speed" | bc -l)
	exposure=$(echo "scale=20; $aperture * $aperture / $speeds" | bc -l)
	nc=$(echo "$exposure" | wc -c)
	exposure2=""
	for j in $(seq $nc 100); do
		exposure2="0$exposure2"
	done
	exposure2="$exposure2$exposure"
	echo "aperture=$aperture  speed=$speed  speeds=$speeds  exposure=$exposure"
	echo "$exposure2 $i" >> exposures.txt
	echo "$img" >> images.txt
	shift
done

exit

sort -r -n exposures.txt > tmp.txt
rm exposures.txt
mv tmp.txt exposures.txt
cat exposures.txt

tifflist=""

for i in $(seq 1 $nimg); do
	imgid=$(head -n $i exposures.txt | tail -n 1 | cut -d" " -f 2)
	img=$(cat images.txt | sed -n ${imgid}p)
	echo -n "Converting $img..."
	pfbatch "$img" "$rawpreset" "$img.tif" >& "$img.log"
	echo " done."
	tifflist="$tifflist $img.tif"
done

echo "align_image_stack -v --use-given-order -s 0 -a aligned $tifflist"
rm -f aligned*.tif
align_image_stack -v --use-given-order -s 0 -a aligned $tifflist
ls -1 aligned*.tif > aligned.txt

#exit

refexp=$(head -n 1 exposures.txt | cut -d" " -f 1)

plist=""
for i in $(seq 2 $nimg); do
	exp=$(head -n $i exposures.txt | tail -n 1 | cut -d" " -f 1)
	imgid=$(head -n $i exposures.txt | tail -n 1 | cut -d" " -f 2)
	echo "imgid: $imgid"
	#img=$(cat images.txt | sed -n ${imgid}p)
	img=$(cat aligned.txt | sed -n ${i}p)
	r=$(echo "scale=20; $exp / $refexp" | bc -l)
	echo "r: $r"
	cat "$scriptdir/blend.pfp" | sed "s/<property name=\"exposure\" value=\"1\">/<property name=\"exposure\" value=\"$r\">/g" > blend${i}.pfp
	sed -i.bak "s|%image%|$(pwd)/$img|g" blend${i}.pfp
	
	plist="$plist blend${i}.pfp"

done

pfbatch $(ls -1 aligned*.tif | head -n 1) $plist blend.pfi >& blend.pfi.log

rm $plist aligned.txt exposures.txt images.txt
